package com.music.vivi.desktop

/**
 * Desktop string table. English is the primary (source) language; other
 * languages fall back to English until their translations are added under
 * the matching locale tag (e.g. `"it" to mapOf("search" to "Cerca", ...)`).
 *
 * The maps themselves live in `LocalizationTablesN.kt` (one class cannot hold
 * every literal). This file is GENERATED by
 * `scripts/generate_desktop_localization.py` from the Android app's
 * `strings.xml` resources — do not edit by hand.
 */
object Localization {
    private val strings: Map<String, Map<String, String>> = mapOf(
        "en" to strings_0(),
        "ar" to strings_1(),
        "as" to strings_2(),
        "az" to strings_3(),
        "be" to strings_4(),
        "bg" to strings_5(),
        "bn" to strings_6(),
        "bs" to strings_7(),
        "ca" to strings_8(),
        "cs" to strings_9(),
        "de" to strings_10(),
        "el" to strings_11(),
        "es" to strings_12(),
        "et" to strings_13(),
        "eu" to strings_14(),
        "fa" to strings_15(),
        "fi" to strings_16(),
        "fil" to strings_17(),
        "fr" to strings_18(),
        "hi" to strings_19(),
        "hr" to strings_20(),
        "hu" to strings_21(),
        "id" to strings_22(),
        "in" to strings_23(),
        "it" to strings_24(),
        "iw" to strings_25(),
        "ja" to strings_26(),
        "km" to strings_27(),
        "ko" to strings_28(),
        "lt" to strings_29(),
        "ml" to strings_30(),
        "ms" to strings_31(),
        "nb" to strings_32(),
        "nb-rNO" to strings_33(),
        "nl" to strings_34(),
        "pa" to strings_35(),
        "pl" to strings_36(),
        "pt" to strings_37(),
        "pt-rBR" to strings_38(),
        "ro" to strings_39(),
        "ru" to strings_40(),
        "sk" to strings_41(),
        "sl" to strings_42(),
        "sr" to strings_43(),
        "sv" to strings_44(),
        "ta" to strings_45(),
        "te" to strings_46(),
        "th" to strings_47(),
        "tr" to strings_48(),
        "uk" to strings_49(),
        "vi" to strings_50(),
        "zh-rCN" to strings_51(),
        "zh-rTW" to strings_52(),
    )
    fun get(language: String, key: String): String {
        val direct = strings[language]?.get(key)
        if (direct != null) return direct
        strings["en"]?.get(key)?.let { return it }
        // Safety net: a missing translation must never surface as a raw snake-
        // case key on screen. Fall back to the first dictionary that has a real
        // (non-key) translation, so even a gap in every map shows something
        // readable instead of "player_background_visualizer".
        for (map in strings.values) {
            map[key]?.takeIf { it != key }?.let { return it }
        }
        return key
    }
}
