#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the Fedora/RPM spec (and its .desktop file) for a VIVI Music DE release.

Run by .github/workflows/build-desktop-linux.yml. jpackage itself can emit an
RPM, but this package is built from the jpackage **app image** with a
hand-written spec instead, for two reasons:

  1. the uninstall cleanup is inlined into the `%postun` scriptlet. RPM keeps
     scriptlets inside its header, so — unlike the .deb, which needs a helper
     file copied to /usr/share because dpkg removes the payload before postrm —
     nothing has to survive the erase: `dnf remove vivi-music-de` keeps exactly
     one final backup of every `~/.vivimusic` and wipes all the caches, the same
     behavior as the Windows, .deb and AUR uninstallers;
  2. the layout matches the AUR PKGBUILD (scripts/generate_aur_pkgbuild.py)
     path-for-path, so a Fedora user and an Arch user get the same install, and
     the metadata says `PiBOH` / `GPL-3.0-or-later` / `Applications/Multimedia`
     instead of jpackage's generic values.

The cleanup body is NOT duplicated here: it is read from
`scripts/uninstall-cleanup.sh`, the single source of truth shared by Linux and
macOS.

Package layout:

    /opt/vivi-music-de/…                                   the app image
    /usr/bin/vivi-music-de                                 launcher symlink
    /usr/share/applications/vivi-music-de.desktop
    /usr/share/icons/hicolor/1024x1024/apps/vivi-music-de.png

Usage:
    python3 scripts/generate_rpm_spec.py --out DIR --version 1.52.7
"""

import argparse
import os
import sys
from pathlib import Path

CLEANUP_SOURCE = Path(__file__).resolve().parent / "uninstall-cleanup.sh"

PKG_NAME = "vivi-music-de"
APP_DIR = "/opt/vivi-music-de"

DESKTOP_ENTRY = """\
[Desktop Entry]
Name=VIVI Music DE
GenericName=Music Player
Comment=Desktop music player for YouTube Music
Exec={app_dir}/bin/VIVIMusic %U
Icon={pkg}
Terminal=false
Type=Application
Categories=AudioVideo;Audio;Player;
Keywords=music;youtube;player;audio;
StartupWMClass=VIVIMusic
"""


def indent(text: str, prefix: str = "    ") -> str:
    out = []
    for line in text.splitlines():
        out.append(prefix + line if line.strip() else "")
    return "\n".join(out)


def read_cleanup_body() -> str:
    """The shared cleanup script, without its shebang and with CRLF normalized."""
    if not CLEANUP_SOURCE.is_file():
        print(f"error: {CLEANUP_SOURCE} not found", file=sys.stderr)
        sys.exit(1)
    text = CLEANUP_SOURCE.read_text(encoding="utf-8").replace("\r\n", "\n")
    lines = text.splitlines()
    if lines and lines[0].startswith("#!"):
        lines = lines[1:]
    return "\n".join(lines).strip("\n")


def build_spec(version: str, cleanup_body: str) -> str:
    # RPM expands macros inside scriptlets, so a literal '%' in the inlined
    # shell body would have to be doubled. The cleanup script has none, and this
    # guard makes that a hard requirement instead of a silent breakage.
    if "%" in cleanup_body:
        print("error: uninstall-cleanup.sh contains a '%', which RPM would treat as a macro", file=sys.stderr)
        sys.exit(1)

    return """\
# Generated by scripts/generate_rpm_spec.py for VIVI Music DE {version}.
# Build with:  rpmbuild --define "_topdir <dir>" -bb vivi-music-de.spec
# <dir>/SOURCES must contain: vivi-music-app-{version}.tar.gz (the jpackage
# app image, its contents at the tarball root) and vivi-music-de.png.

Name:           {pkg}
Version:        {version}
Release:        1%{{?dist}}
Summary:        VIVI Music DE - native desktop edition of VIVI Music
License:        GPL-3.0-or-later
URL:            https://github.com/PiBOH/vivi-music-de
Vendor:         PiBOH
Group:          Applications/Multimedia
Source0:        vivi-music-app-%{{version}}.tar.gz
Source1:        {pkg}.desktop
Source2:        {pkg}.png
BuildArch:      x86_64
# The app image ships its own JRE, so the only requirements are the system
# libraries the bundled binaries link against: rpmbuild detects those sonames
# automatically (AutoReqProv). Fedora resolves them (`dnf` maps
# `libgtk-3.so.0()(64bit)` to the providing package), which keeps the package
# installable on every RPM distribution instead of hard-coding Fedora names.
AutoReqProv:    yes

# Bundling a runtime means hundreds of pre-built .so files: do not let rpmbuild
# strip them (the AUR package uses the same '!strip' option), and do not build a
# debuginfo subpackage out of a bundled JRE.
%global __strip /bin/true
%global __objcopy /bin/true
%global debug_package %{{nil}}

%description
VIVI Music Desktop Edition is a Material 3 desktop music player for YouTube
Music, built with Compose Multiplatform.

This is the native Fedora/RPM package: it is fully self-contained (bundled
runtime, no system Java required) and installs under {app_dir}.

%prep
%setup -q -c

%install
rm -rf %{{buildroot}}
mkdir -p %{{buildroot}}{app_dir}
# %setup -c left the app image unpacked in the build subdirectory, which is also
# the working directory rpm enters for %install, so copy from '.'.
cp -a . %{{buildroot}}{app_dir}/
install -Dm644 %{{SOURCE1}} %{{buildroot}}%{{_datadir}}/applications/{pkg}.desktop
install -Dm644 %{{SOURCE2}} %{{buildroot}}%{{_datadir}}/icons/hicolor/1024x1024/apps/{pkg}.png
mkdir -p %{{buildroot}}%{{_bindir}}
ln -s {app_dir}/bin/VIVIMusic %{{buildroot}}%{{_bindir}}/{pkg}

%post
# Refresh the launcher database and the icon cache so the app shows up in the
# Fedora app grid right away (quietly, and never fail an install over it).
update-desktop-database -q >/dev/null 2>&1 || :
gtk-update-icon-cache -q -t -f %{{_datadir}}/icons/hicolor >/dev/null 2>&1 || :

%postun
update-desktop-database -q >/dev/null 2>&1 || :
gtk-update-icon-cache -q -t -f %{{_datadir}}/icons/hicolor >/dev/null 2>&1 || :
# $1 == 0 means the package is being erased (not upgraded), so this is where the
# user data is cleaned: keep exactly ONE backup (the newest .vivide.backup) plus
# device-sync.json, and delete every cache (updates, audio, video/canvas,
# lyrics, logs, …) for every user. Runs as root, hence the /home/* loop.
if [ "$1" = "0" ]; then
{cleanup}
fi

%files
{app_dir}
%{{_bindir}}/{pkg}
%{{_datadir}}/applications/{pkg}.desktop
%{{_datadir}}/icons/hicolor/1024x1024/apps/{pkg}.png
""".format(
        version=version,
        pkg=PKG_NAME,
        app_dir=APP_DIR,
        cleanup=indent(cleanup_body, "    "),
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, help="Directory for the generated spec + .desktop")
    parser.add_argument("--version", required=True, help="DE version, e.g. 1.52.7")
    args = parser.parse_args()

    version = args.version.strip()
    if not version or "-" in version:
        print(f"error: '{version}' is not a valid RPM version (no '-')", file=sys.stderr)
        sys.exit(1)

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    spec_path = out / f"{PKG_NAME}.spec"
    desktop_path = out / f"{PKG_NAME}.desktop"

    spec_path.write_text(build_spec(version, read_cleanup_body()), encoding="utf-8", newline="\n")
    desktop_path.write_text(
        DESKTOP_ENTRY.format(app_dir=APP_DIR, pkg=PKG_NAME), encoding="utf-8", newline="\n"
    )

    print(f"Wrote {spec_path} and {desktop_path} (version {version})")


if __name__ == "__main__":
    main()
